### ISSUE TITLE
build in macOS failed: ld: library not found for -lcrypto

### ISSUE THREAD

**Issue by Alanscut** [Pintulalm/Restweb#11]
**Describe the bug**
when compile it in mac with mac branch, after making the project, the making progress reached 100%, but it still report an error: ld: library not found for -lcrypto.

<img width="502" alt="crypto" src="https://user-images.githubusercontent.com/21104054/75627493-a15f6280-5c0b-11ea-9d4b-fb102cb25fa0.png">

**To Reproduce**
1. cmake . (in mac branch, install cpprestsdk with brew)
2. make
3. failed..

before I installed openssl to the /usr/local/lib, make failed when progress reached 33%, because openssl installed in another non-standard path. after I install openssl to /usr/local/lib, the make could reach 100%, but it still report the same error, this annoyed me 😢 

**Expected behavior**
make successfully.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS 10.15
 - CMake 3.14.3
 - clang 11.0.0

**Additional context**
building it successfully in windows and ubuntu.

**Comment by Meenapintu** [comment]
This looks a common OpenSSL issue for mac.

Hopefully these links might help you. 

link : https://github.com/ValveSoftware/source-sdk-2013/issues/413
link : https://github.com/Meenapintu/Restweb/issues/7

**Comment by Alanscut** [comment]
thanks! this is really not a business of restweb, I should make some configuration for openssl in my mac.
