### ISSUE TITLE
undefined reference to symbol 'pthread_cond_clockwait@@GLIBC_2.30'

### ISSUE THREAD

**Issue by Alexander-Degtyar** [Pintulalm/Restweb#12]
I faced the following error during build on Linux:
```
/usr/bin/ld: CMakeFiles/restserver.dir/main.cpp.o: undefined reference to symbol 'pthread_cond_clockwait@@GLIBC_2.30'
/usr/bin/ld: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
```
Environment:
gcc 10.2.0
cmake 3.19.5
Arch Linux: 5.10.16-arch1-1

Solution:
POSIX threads need to be linked.

**Comment by Meenapintu** [comment]
Thanks @Alexander-Degtyar  for providing the fix also . I've merged  pull request of  fix in mainline .
