### ISSUE TITLE
cmake configuration

### ISSUE THREAD

**Issue by amigo421** [Pintulalm/Restweb#2]
this is a feature request, not a bug.
is it possible for you to extend cmakelists with 
ExternalProject_Add statement for auto-cloning and build casablanca prior of your project build will be started?

P.S. could you also add a requirements into readme ? my compiler could not find pqxx headers.
if you'd add "PostgreSQL required" , it would be clear for a starting

**Comment by Meenapintu** [comment]
Thanks for  suggestion, I will extend it with requested feature and try to make more clear structure of repo.

(if you have already done it , you are welcome to contribute so it can be helpful to others )

PostgreSQL is not require  neither pqxx  if you are just working with Restweb.

as I have mentioned in readme of root root folder . 

>{ #dbms folder is a independent project right now to access database}


Happy coding  👍

**Comment by amigo421** [comment]
to avoid a raising one more tracker request - just a remark about project organization:
I see a few files which are auto-generated, not a source, depends of the dev host and will be overwritten after cloning in any case
I suggest to remove this from repository:
 - Restweb.cbp - this is one of cmake generated files , which is not used directly (usually)
 - CMakeCache.txt - this is also auto-generated file and very specific of OS and used toolchains
 - Makefile - as far as I understand your project cmake based, so makefile is also produced by cmake, isn't it? 
 - layout file is also IDE specific and usually is not included into the projects on github, isn't it? 

P.S. let me try to implement auto-cloning/build of casablanca directly from the project cmakelists. 
not sure that will okay, let me try. will update you in some time.

**Comment by Meenapintu** [comment]
Yes , there are some auto-generated files also .I will be removing then from git tracker in sort time . 
Thanks for advice,it is a great advice not to include sys-generated files.

You are trying to implement auto-cloning/build , please do so . it will be very helpful to everyone. 

Thank you  , waiting for your update .
