### ISSUE TITLE
Using the REST server in LAN

### ISSUE THREAD

**Issue by weeyongjun** [Pintulalm/Restweb#5]
Hi i'm quite new to programming, and need some help. I am able to get the server and example RestWeb server up and running, and it works fine in localhost (http://localhost:34568/). But when i try to use another computer to access via IP address (http://(IP address):34568/) using LAN it does not work. i tested it locally again via IP address and it also doesn't work. anyone has any solution?

I'm setting up the cpprestsdk in Raspberry Pi 2, Ubuntu Mate 16.04. I'm trying to use the SDK to build a REST API service.

BTW, i noticed that the MAKE process for installing the RestWeb server will have errors, but can be resolved by adding -lpthread in the CMakeLists.txt

**Comment by Meenapintu** [comment]
Hi @weeyongjun  , may be it's because of your firewall settings like port is blocked etc. because I have tested it with proxy server and without proxy and as you mentioned that it works fine on local host. 

Anyway I will try to find the solution by  end of day .

**Comment by weeyongjun** [comment]
Hi,
Thanks for getting back. i realized that you hard-coded the address to look up localhost inside main.cpp. after modification, it is working now..

**Comment by weeyongjun** [comment]
if you can update main.cpp to lookup machine's IP address, that will be great. Nevertheless i will look into it.

**Comment by Meenapintu** [comment]
Okay , I will do it
