### ISSUE TITLE
Will not build in vs2017

### ISSUE THREAD

**Issue by aprole** [Pintulalm/Restweb#8]
I cannot get this project to build in vs2017, even using the vsc15_v140 branch. It says there are missing packages from NuGet that are required to install. Should this really require NuGet? I installed CppRestSDK with vcpkg. The cpprestsdk github page advises against using Nuget. I don't see any references to any other libraries in the source code other than cpprest, why wouldn't it work with cpprestsdk installed with vcpkg?

**Comment by Meenapintu** [comment]
Please post logs also if you aren't able to build on windows.
